"""empty message

Revision ID: 481d94818d45
Revises: 23ffc6fdcdbb
Create Date: 2014-06-08 23:34:58.255097

"""

# revision identifiers, used by Alembic.
revision = '481d94818d45'
down_revision = '23ffc6fdcdbb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlist', sa.Column('slug', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playlist', 'slug')
    ### end Alembic commands ###
