"""empty message

Revision ID: 57fbbf6367c0
Revises: 22d87ecff971
Create Date: 2014-06-09 05:57:51.932723

"""

# revision identifiers, used by Alembic.
revision = '57fbbf6367c0'
down_revision = '22d87ecff971'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlist_element', sa.Column('thumbnail', sa.String(length=255), nullable=True))
    op.add_column('playlist_element', sa.Column('title', sa.String(length=255), nullable=True))
    op.drop_column('playlist_element', 'name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlist_element', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('playlist_element', 'title')
    op.drop_column('playlist_element', 'thumbnail')
    ### end Alembic commands ###
